name: streamflow
description: StreamFlow release browser and universal cast controller.
publish_to: "none"
version: 1.0.0+10

environment:
  sdk: ">=3.12.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  webview_flutter: 4.14.1
  bonsoir: 7.1.5
  http: 1.6.0
  file_selector: 1.1.0
  shared_preferences: 2.5.5
  mime: 2.0.0
  flutter_chrome_cast: 1.4.6
  flutter_to_airplay: 2.1.0
  upnp_client: 1.0.4
  permission_handler: 12.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 6.0.0

flutter:
  uses-material-design: true
